In [11]:
import pandas as pd
import numpy as np
from UtilityFunctions import ReadData, WriteData
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [12]:
train_features, train_labels, test_features = ReadData()

In [16]:
print(train_features)

  (0, 2)	1.0
  (0, 28)	1.0
  (0, 58)	1.0
  (0, 69)	1.0
  (1, 4)	1.0
  (1, 21)	1.0
  (1, 46)	1.0
  (1, 71)	1.0
  (2, 8)	1.0
  (2, 22)	1.0
  (2, 53)	1.0
  (2, 72)	1.0
  (3, 4)	1.0
  (3, 31)	1.0
  (3, 58)	1.0
  (3, 67)	1.0
  (4, 11)	1.0
  (4, 28)	1.0
  (4, 54)	1.0
  (4, 70)	1.0
  (5, 7)	1.0
  (5, 38)	1.0
  (5, 46)	1.0
  (5, 60)	1.0
  (6, 5)	1.0
  :	:
  (111993, 66)	1.0
  (111994, 11)	1.0
  (111994, 32)	1.0
  (111994, 52)	1.0
  (111994, 70)	1.0
  (111995, 5)	1.0
  (111995, 35)	1.0
  (111995, 50)	1.0
  (111995, 63)	1.0
  (111996, 2)	1.0
  (111996, 29)	1.0
  (111996, 52)	1.0
  (111996, 76)	1.0
  (111997, 15)	1.0
  (111997, 25)	1.0
  (111997, 46)	1.0
  (111997, 61)	1.0
  (111998, 8)	1.0
  (111998, 27)	1.0
  (111998, 45)	1.0
  (111998, 76)	1.0
  (111999, 12)	1.0
  (111999, 25)	1.0
  (111999, 52)	1.0
  (111999, 76)	1.0


In [4]:
label= LabelEncoder()
for i in range(train_features.shape[1]):
    train_features[:,i]= label.fit_transform(train_features[:,i])
    test_features[:,i]= label.transform(test_features[:,i])

In [5]:
print(train_features[0:2,:].astype(np.int))

[[2 8 1 9]
 [4 1 6 1]]


In [14]:
one=OneHotEncoder()
train_features = one.fit_transform(train_features)
test_features=one.transform(test_features)

In [15]:
print(train_features[0:2,:])

  (0, 2)	1.0
  (0, 28)	1.0
  (0, 58)	1.0
  (0, 69)	1.0
  (1, 4)	1.0
  (1, 21)	1.0
  (1, 46)	1.0
  (1, 71)	1.0


In [6]:
train_features = train_features.astype(np.int)
test_features = test_features.astype(np.int)

In [7]:
X_train, X_val, y_train, y_val = train_test_split(train_features, train_labels, test_size= 0.2)

In [8]:
print(X_train[0:2,:])

[[1 7 1 9]
 [1 2 9 1]]


In [ ]:
y_val_pred  = model.predict(X_val)

In [ ]:
f1 = f1_score(y_val_pred,y_val)
print(f1)

In [ ]:
y_test_pred = model.predict(test_features)

In [ ]:
WriteData(y_test_pred, filename = 'submission1')

In [ ]:
X_train.shape

In [ ]:
print(X_train[0:2,:])

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
y_pre=lr.predict(X_val)
print('F1-Score : ',f1_score(y_val,y_pre))

F1-Score :  0.0
